apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptofollow-frontend
  namespace: cryptofollow-main
  labels:
    app: cryptofollow-frontend
spec:
  selector:
    matchLabels:
      name: cryptofollow-frontend-pod
      app: cryptofollow-frontend
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      name: cryptofollow-frontend-pod
      labels:
        name: cryptofollow-frontend-pod
        app: cryptofollow-frontend
    spec:
      containers:
        - name: cryptofollow-frontend
          image: cryptofollow.cloud:32000/cryptofollow-frontend-main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # resources:
          # requests:
          #   memory: '200Mi'
          #   cpu: '100m'
          # limits:
          #   memory: '500Mi'
          #   cpu: '200m'
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 10 # how long to wait before checking
            periodSeconds: 10 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 50 # how many failures to accept before failing
            timeoutSeconds: 10 # how long to wait for a response
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 5 # how long to wait before checking
            periodSeconds: 5 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 50 # how many failures to accept before failing
            timeoutSeconds: 10
          envFrom:
            # - secretRef:
            #     name: cryptofollow-frontend-env
            - configMapRef:
                name: cryptofollow-frontend-cm
